# render.yaml (NİHAİ VE BASİTLEŞTİRİLMİŞ HALİ)

services:
  # Artık sadece TEK BİR servisimiz var. Bu, main.py'yi çalıştıran ana botumuz.
  - type: worker
    name: macro-news-analyzer # Servis adını daha genel yapabiliriz
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - fromGroup: news-bot-secrets # API anahtarlarımızı buradan alacak
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 5