# Doğru ve Çalışacak Olan render.yaml Kodu

services:
  # Servis 1: Canlı haber botu (diski ilk kez bu servis oluşturacak)
  - type: worker
    name: news-analyzer-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - fromGroup: news-bot-secrets
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 5 # Disk burada oluşturuluyor

  # Servis 2: Veritabanı güncelleyici (yukarıda oluşturulan diski kullanacak)
  - type: cron
    name: database-updater
    env: python
    schedule: "0 3 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_update.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - fromGroup: news-bot-secrets
    disk:
      name: data-disk
      mountPath: /data # Sadece bağlanacağı yolu ve ismi belirtmek yeterli