services:
  # Servis 1: Sürekli çalışacak olan canlı haber analiz botu
  - type: worker
    name: news-analyzer-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - fromGroup: news-bot-secrets
    # DEĞİŞİKLİK: Disk tanımı doğrudan servisin içine, "disk:" (tekil) olarak yazılıyor.
    # Diski ilk kez burada tanımladığımız için boyutunu (sizeGB) belirtiyoruz.
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 5

  # Servis 2: Veritabanını periyodik olarak güncelleyecek olan Cron Job
  - type: cron
    name: database-updater
    env: python
    schedule: "0 3 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_update.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - fromGroup: news-bot-secrets
    # DEĞİŞİKLİK: Bu servis, yukarıda zaten oluşturulmuş olan diski kullanıyor.
    # Sadece ismini ve bağlanacağı yolu belirtmemiz yeterli.
    disk:
      name: data-disk
      mountPath: /data